import { useEffect, useId, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api } from '../api'
import { ErrorState, Loading } from '../components/AsyncState'
import type { RuleSummary } from '../types'

function fileSize(bytes: number) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1048576) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / 1048576).toFixed(1)} MB` }
export default function NewRunPage() {
  const [rules, setRules] = useState<RuleSummary[]>([]), [ruleId, setRuleId] = useState(''), [file, setFile] = useState<File>(), [loading, setLoading] = useState(true), [error, setError] = useState(''), [submitting, setSubmitting] = useState(false), [dragging, setDragging] = useState(false)
  const inputId = useId(), input = useRef<HTMLInputElement>(null), navigate = useNavigate()
  const load = () => { setLoading(true); setError(''); api.rules().then((items) => { setRules(items); setRuleId((old) => old || items[0]?.id || '') }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(load, [])
  const accept = (candidate?: File) => { if (!candidate) return; if (!candidate.name.toLowerCase().endsWith('.zip')) { setError('请选择 .zip 格式的作业压缩包'); return } setError(''); setFile(candidate) }
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!file || !ruleId || submitting) return; setSubmitting(true); setError(''); try { const run = await api.createRun(file, ruleId); navigate(`/runs/${run.id}`) } catch (e) { setError((e as Error).message); setSubmitting(false) } }
  return <section className="page narrow"><div className="page-heading"><p className="eyebrow">NEW CHECK</p><h1>新建检查</h1><p>选择老师提供的规则，然后上传你的作业压缩包。</p></div>{loading ? <Loading label="正在读取检查规则…" /> : error && rules.length === 0 ? <ErrorState message={error} retry={load} /> : <form className="form-card" onSubmit={submit} noValidate><div className="step-label"><span>1</span><div><b>选择检查规则</b><small>规则决定必需文件、构建与测试方式</small></div></div><label htmlFor="rule">课程规则</label><select id="rule" value={ruleId} onChange={(e) => setRuleId(e.target.value)} required>{rules.map((rule) => <option value={rule.id} key={rule.id}>{rule.name} · {rule.language.toUpperCase()}</option>)}</select><div className="divider" /><div className="step-label"><span>2</span><div><b>上传作业</b><small>仅接受 ZIP，服务端会执行安全解压检查</small></div></div><label className={`drop-zone ${dragging ? 'is-dragging' : ''}`} htmlFor={inputId} onDragOver={(e) => { e.preventDefault(); setDragging(true) }} onDragLeave={() => setDragging(false)} onDrop={(e) => { e.preventDefault(); setDragging(false); accept(e.dataTransfer.files[0]) }}><input ref={input} id={inputId} aria-label="作业 ZIP" type="file" accept=".zip,application/zip" onChange={(e) => accept(e.target.files?.[0])} /><span className="upload-mark" aria-hidden="true">↑</span>{file ? <><strong>{file.name}</strong><small>{fileSize(file.size)} · 点击更换文件</small></> : <><strong>拖放 ZIP 到这里，或点击选择</strong><small>文件大小上限由服务端安全策略决定</small></>}</label>{error && <p className="inline-error" role="alert">{error}</p>}<aside className="safety-note"><b>安全说明</b><p>上传内容按不可信数据处理。命令执行默认关闭；即使启用受控子进程，也不等同于完整沙箱。</p></aside><button className="button button--primary button--wide" disabled={!file || !ruleId || submitting}>{submitting ? <><span className="spinner spinner--small" /> 正在创建检查…</> : '启动检查'}</button></form>}</section>
}
