import { cleanup, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import App from './App'

const rules = [{ rule: { id: 'python-course-v1', name: 'Python 课程作业', language: 'python', schema_version: 1 }, revision: 'abc', builtin: true }]
const report = { run_id: 'run-1', project_name: 'homework.zip', status: 'FAIL', stage: 'complete', rule_id: 'python-course-v1', rule_name: 'Python 课程作业', rule_version: 1, started_at: '2026-07-11T10:00:00Z', finished_at: '2026-07-11T10:00:02Z', duration_ms: 2000, checks: [{ id: 'required', label: '必需文件', category: 'structure', status: 'PASS', message: 'main.py 已找到', suggestion: '' }, { id: 'tests', label: '测试', category: 'test', status: 'FAIL', message: '1 failed', suggestion: '修复断言' }, { id: 'style', label: '临时文件', category: 'hygiene', status: 'WARN', message: '发现缓存', suggestion: '删除缓存' }], build: { command: ['python', '-m', 'py_compile', 'main.py'], return_code: 0, duration_ms: 120, timed_out: false, stdout: 'ok', stderr: '' }, test: { command: ['python', '-m', 'pytest'], return_code: 1, duration_ms: 1000, timed_out: false, stdout: 'x'.repeat(3000), stderr: 'assert 1 == 2' }, security_warnings: [], environment: { runner: 'controlled-subprocess', sandboxed: false } }

function json(data: unknown, status = 200) { return Promise.resolve(new Response(JSON.stringify(data), { status, headers: { 'Content-Type': 'application/json' } })) }
function mount(path: string) { return render(<MemoryRouter initialEntries={[path]}><App /></MemoryRouter>) }

afterEach(() => { cleanup(); vi.unstubAllGlobals() })

describe('SubmitReady UI', () => {
  it('展示首页并可进入新建检查', async () => { vi.stubGlobal('fetch', vi.fn(() => json(rules))); mount('/'); await userEvent.click(screen.getByRole('link', { name: /开始检查/ })); expect(await screen.findByRole('heading', { name: '新建检查' })).toBeInTheDocument() })
  it('上传表单展示文件大小、规则并防止重复提交', async () => { const fetchMock = vi.fn((url: string, init?: RequestInit) => { void init; return url.endsWith('/rules') ? json(rules) : json({ id: 'run-1', status: 'RUNNING', stage: 'extracting' }, 201) }); vi.stubGlobal('fetch', fetchMock); mount('/new'); expect(await screen.findByRole('option', { name: /Python 课程作业/ })).toBeInTheDocument(); const file = new File(['zipdata'], 'work.zip', { type: 'application/zip' }); await userEvent.upload(screen.getByLabelText('作业 ZIP'), file); expect(screen.getByText(/7 B/)).toBeInTheDocument(); const button = screen.getByRole('button', { name: '启动检查' }); await userEvent.click(button); expect(button).toBeDisabled(); await waitFor(() => expect(fetchMock.mock.calls.filter((call) => call[1]?.method === 'POST')).toHaveLength(1)) })
  it('规则加载失败时展示可重试错误状态', async () => { vi.stubGlobal('fetch', vi.fn(() => json({ error: { code: 'DOWN', message: '服务暂不可用' } }, 503))); mount('/new'); expect(await screen.findByRole('alert')).toHaveTextContent('服务暂不可用'); expect(screen.getByRole('button', { name: '重试' })).toBeInTheDocument() })
  it('报告渲染统计、导出和长日志折叠', async () => { vi.stubGlobal('fetch', vi.fn(() => json(report))); mount('/runs/run-1/report'); expect(await screen.findByText('homework.zip')).toBeInTheDocument(); expect(screen.getByText('1 项通过')).toBeInTheDocument(); expect(screen.getByText('1 项警告')).toBeInTheDocument(); expect(screen.getByText('1 项失败')).toBeInTheDocument(); expect(screen.getByRole('link', { name: '导出 JSON' })).toHaveAttribute('href', '/api/runs/run-1/export.json'); const expand = screen.getByRole('button', { name: /展开完整日志/ }); await userEvent.click(expand); expect(expand).toHaveTextContent('收起日志') })
  it('历史记录渲染并删除', async () => { const fetchMock = vi.fn((url: string, init?: RequestInit) => init?.method === 'DELETE' ? Promise.resolve(new Response(null, { status: 204 })) : json([{ id: 'run-1', project_name: 'homework.zip', rule_name: 'Python 课程作业', status: 'PASS', stage: 'completed', started_at: '2026-07-11T10:00:00Z', duration_ms: 800 }])); vi.stubGlobal('fetch', fetchMock); vi.stubGlobal('confirm', vi.fn(() => true)); mount('/history'); expect(await screen.findByText('homework.zip')).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: /删除 homework.zip/ })); expect(await screen.findByText('暂无检查记录')).toBeInTheDocument() })
  it('规则页展示内置规则、模板下载和导入校验错误', async () => { const fetchMock = vi.fn((url: string, init?: RequestInit) => init?.method === 'POST' ? json({ error: { code: 'INVALID_RULE', message: '规则版本不受支持', details: [{ loc: ['schema_version'], msg: '必须为 1' }] } }, 422) : json(rules)); vi.stubGlobal('fetch', fetchMock); mount('/rules'); expect(await screen.findByText('Python 课程作业')).toBeInTheDocument(); expect(screen.getByRole('link', { name: '下载规则模板' })).toHaveAttribute('href', '/api/rules/template'); await userEvent.upload(screen.getByLabelText('导入 YAML 规则'), new File(['bad'], 'bad.yaml', { type: 'text/yaml' })); await userEvent.click(screen.getByRole('button', { name: '校验并导入' })); expect(await screen.findByRole('alert')).toHaveTextContent('规则版本不受支持') })
})
